name: Deploy Master
on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t ${{secrets.DOCKER_NAMESPACE }}/amo_service:latest .
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_NAMESPACE }}/amo_service:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ./prod/amo_service_git
            docker compose down || true
            docker rmi ${{ secrets.DOCKER_NAMESPACE }}/amo_servicee:latest }} || true
            docker compose up -d 
